name: Terraform Commands
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
jobs:
  
  my_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        ls -ltr
    - name: Terraform Action
      run: terraform ${{ inputs.command }} -auto-approve -input=false
