name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  setup:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  tf_plan:
    needs: setup
    uses: ./.github/workflows/solution_reusable_workflow.yml
    with:
      command: "plan"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  
  tf_apply:
    needs: tf_plan
    uses: ./.github/workflows/solution_reusable_workflow.yml
    with:
      command: "apply"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      
