name: Terraform Commands
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
jobs:
  terraform-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Action
        run: terraform ${{ inputs.command }} -auto-approve -input=false
