name: Terraform Commands
on:
  workflow_call:
    inputs:
      command:
        description: 'The terraform command to run plan|apply'
        required: true
        type: string
      work_dir:
        description: 'The working directory'
        required: true
        type: string
        default: "."
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  workflow_call:
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        run: |
          case "${{ inputs.command }}" in (plan|apply)
              echo "Running valid command: ${{ inputs.command }}"
              ;;
            *)
              echo "Invalid command: '${{ inputs.command }}'. Allowed: plan, apply"
              exit 1
              ;;
          esac
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud using Workload Identity Federation
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: '232833671864'
          workload_identity_provider: 'projects/232833671864/locations/global/workloadIdentityPools/github-actions-pool/providers/google-beta'
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Action
        run: |
          if [ "${{ inputs.command }}" = "apply" ]; then
            terraform ${{ inputs.command }} -auto-approve -input=false
          else
            terraform ${{ inputs.command }} -input=false
          fi
        working-directory: ${{ inputs.work_dir }} 
