name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  setup:
    name: Checkout and Setup Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: terraform init

  tf_plan:
    needs: setup
    uses: ./.github/workflows/solution_reusable_workflow.yml
    with:
      command: "plan"
  
  tf_apply:
    needs: tf_plan
    uses: ./.github/workflows/solution_reusable_workflow.yml
    with:
      command: "apply"
      
