name: "Deploy Terraform"

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: "write"

jobs:
  setup:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          sparse-checkout: |
            .github

  tf_plan:
    needs: setup
    uses: ./.github/workflows/solution_reusable_workflow.yml
    with:
      command: "plan"
      service_account: ${{ vars.GH_TF_SERVICE_ACCOUNT }}
      project_id: ${{ vars.PROJECT_ID }}
      workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      work_dir: "."
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  
  tf_apply:
    needs: tf_plan
    uses: ./.github/workflows/solution_reusable_workflow.yml
    with:
      command: "apply"
      service_account: ${{ vars.GH_TF_SERVICE_ACCOUNT }}
      project_id: ${{ env.PROJECT_ID }}
      workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      work_dir: "."
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      
