name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  runner-ubuntu: ubuntu-latest
  environment-dev: dev

jobs:
  checkout:
    uses: actions/checkout@v4
